spring:
  cloud:
    gateway:
      default-filters:
        # Add request header
        - AddRequestHeader=X-RequestOrigin, MyReactiveApiGateway
        # Add filter to log request and response
        - LogFilter
        # Add secure headers
        - SecureHeaders
      routes:
        # route testing a POST request only with restrictions
        - id: post-route
          uri: http://httpbin.org/post
          predicates:
            - Path=/post
            - Method=POST
        # route testing a GET request with restrictions and filters
        - id: get-route
          uri: http://httpbin.org/get
          predicates:
            # Only accept requests from host localhost
            - Host=localhost:8080
            # Only accept requests with header key equal "X-UserId" and with numeric values
            - Header=X-UserId, \d+
            # Only accept requests with resource path equal "/get"
            - Path=/get
            # Only accept requests GET requests
            - Method=GET
          filters:
            # Filter to add request header key "X-UserId" and value equal "1234567890"
            - AddRequestHeader=X-UserId, 1234567890